### ISSUE TITLE
Example Working 

### ISSUE THREAD

**Issue by 4Joe** [bbonev/eoip#12]
![image](https://user-images.githubusercontent.com/10292950/93041432-bb780400-f676-11ea-83bc-0f49d07417f1.png)

Suppose I have to build network as in the pictures. 
Do I have to bridge eoip interface to internal LAN interface

Could you provide a working example network?

Best Regards

**Comment by bbonev** [comment]
Normally eoipX interface should be bridged with ethX interface to connect two LANs, but unless the two endpoints of the EoIP tunnel use a private network (even on a private network it is a good idea to encrypt) or some type of encyption of the traffic.

I would rather abstain from giving an example for this, because there are many security considerations in this scenario and IRL it is not considered a good idea to use a plain EoIP tunnel for this type of configuration. Any advise without a detailed knowledge of the network would be a bad advise.

Besides encryption, if we consider all possible attacks (e.g. a MiTM), the topic becomes so vast that it goes out of the scope of this project...
