### ISSUE TITLE
DKMS support

### ISSUE THREAD

**Issue by zouppen** [bbonev/eoip#8]
To make sysops' work easier, DKMS package would make kernel updates smoother because it would build the module automatically during kernel update (until we get this patch to mainline Linux).

https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support

**Comment by bbonev** [comment]
I have already posted the patch to the linux kernel mailing list long-long time ago. The response was that a non-standard proprietary protocol like EOIP would never get included in mainline kernel.

From that perspective DKMS sounds like a good idea.

I am willing to accept DKMS patches, but I cannot do the DKMS part myself because I am not well aware with DKMS itself. Of course I will provide support on the module and kernel programming part in such an effort.

**Comment by RoEdAl** [comment]
[Here](//github.com/RoEdAl/al-eoip) you can find my DKMS EoIP package for *ArchLinux*.

[DKMS configuration file](//github.com/RoEdAl/al-eoip/blob/main/eoip-dkms/dkms.conf) and [Makefile](//github.com/RoEdAl/al-eoip/blob/main/eoip-dkms/Makefile) seems to be very simple.

**Comment by bbonev** [comment]
Thanks, I will look into that and comment here.

**Comment by pertsevds** [comment]
Here is my pull request that adds DKMS support.
